### ISSUE TITLE
multiple pane problem

### ISSUE THREAD

**Issue by mark-hahn** [JavascriptIsMagic/tree-view-git-projects#1]
If I am in one pane and I click on the selected tab in another pane the tree doesn't change.   If I click in a non-selected tab in another pane there is no problem.

windows 8.1
atom 176
this package version 0.1.1

**Comment by JavascriptIsMagic** [comment]
Thank you for pointing that out!

v0.1.2 now uses observeActivePane to properly handle switching between panes.
