### ISSUE TITLE
Tree view steals focus when switching panes or tabs

### ISSUE THREAD

**Issue by dimfeld** [JavascriptIsMagic/tree-view-git-projects#5]
Running Atom 0.182.0 on Mac OS 10.10.2.

This is actually two issues. There's an easy fix for the first one, but I'm not quite sure how to fix the second.
1. The plugin always thinks the project has changed. Normally this isn't an issue, but it came up as I was looking for fixes to the second part of this issue. This happens because (on my system, anyway) there is a difference in trailing slashes between `findProjectRoot` and `atom.project.getPaths`. I added calls to `path.resolve` on line 18 to fix this: `if directory and path.resolve(directory) isnt path.resolve(atom.project.getPaths()[0])`
2. This is the one I don't quite have the right fix for. `treeView.revealActiveFile()` sets the focus to the tree view, which means that any time I switch panes or tabs the focus goes to the tree view. I tried calling `treeView.unfocus()` right after revealActiveFile, which mostly fixes it. 
   Unfortunately it means that when I do a single click in the tree view, it gives focus back to the editor pane, which I think overrides the intended "single click preview" behavior of tree view. I'm not familiar enough with the inner workings of Atom to know if there's a good way to call unfocus conditionally, or if there's some better solution, but hopefully there's some way that can be done.

**Comment by dimfeld** [comment]
Oh, I see that you _removed_ calls to path.resolve as a fix for #4, which means my fix for the first part here may break that. Perhaps a simpler method of just checking for and removing a trailing slash on both strings is preferable.

**Comment by JavascriptIsMagic** [comment]
I am actually hopeful that v0.2.2 will fix both these issues, however I have noticed that a few other packages can really mess with focus a lot as well (particularly preview-plus I have had difficulty with in the past) This patch seems to fix the focus issue for me and preview-plus at least, thank you for pointing out `treeView.unfocus()`

As for the `path.resolve` I added it back in, but only at the point of comparison. Hopefully this will solve compatibility issues across platforms. Please let me know if this fixes the problem for you!

I would ideally have this be cross-platform but without a mac to test it on it makes it difficult to debug these issues.

**Comment by dimfeld** [comment]
Just updated to 0.2.2 and it's looking good to me. Thanks!
